language: go

go:
- 1.11.x

env:
  global:
  - REPO_OWNER=guangie88
  - REPO_NAME=terraform-provider-smallutil

matrix:
  fast_finish: true
  include:
  - env:
    - GOOS=linux
    - GOARCH=386
    - LDFLAGS=
  - env:
    - GOOS=linux
    - GOARCH=amd64
    - LDFLAGS=-linkmode external -extldflags -static -s -w
  - env:
    - GOOS=linux
    - GOARCH=arm
    - LDFLAGS=
  - env:
    - GOOS=linux
    - GOARCH=arm64
    - LDFLAGS=
  - env:
    - GOOS=darwin
    - GOARCH=386
    - LDFLAGS=
  - env:
    - GOOS=darwin
    - GOARCH=amd64
    - LDFLAGS=
  - env:
    - GOOS=darwin
    - GOARCH=arm
    - LDFLAGS=
  - env:
    - GOOS=darwin
    - GOARCH=arm64
    - LDFLAGS=
  - env:
    - GOOS=windows
    - GOARCH=386
    - LDFLAGS=
  - env:
    - GOOS=windows
    - GOARCH=amd64
    - LDFLAGS=

script:
- printf -- "--------\n${GOOS}_${GOARCH} (ldflag \"${LDFLAGS}\")\n--------\n"
- go test ./...
- go build -v -ldflags "${LDFLAGS}"
- zip -j ${REPO_NAME}_${GOOS}_${GOARCH}.zip ${REPO_NAME}

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "${REPO_NAME}_${GOOS}_${GOARCH}.zip"
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(-\S*)?$/
