language: go

go:
- 1.11.x

env:
  global:
  - REPO_OWNER=guangie88
  - REPO_NAME=terraform-provider-smallutil

matrix:
  fast_finish: true
  include:
  # Do not use GOOS and GOARCH because Travis will reinitialize these env vars
  # when bootstrapping Golang set-up
  - env:
    - goos=linux
    - goarch=386
    - ldflags=""
  - env:
    - goos=linux
    - goarch=amd64
    - ldflags=""
  - env:
    - goos=linux
    - goarch=arm
    - ldflags=""
  - env:
    - goos=linux
    - goarch=arm64
    - ldflags=""
  - env:
    - goos=darwin
    - goarch=386
    - ldflags=""
  - env:
    - goos=darwin
    - goarch=amd64
    - ldflags=""
  - env:
    - goos=darwin
    - goarch=arm
    - ldflags=""
  - env:
    - goos=darwin
    - goarch=arm64
    - ldflags=""
  - env:
    - goos=windows
    - goarch=386
    - ldflags=""
  - env:
    - goos=windows
    - goarch=amd64
    - ldflags=""

script:
- printf -- "--------\n${goos}_${goarch} (ldflag \"${ldflags}\")\n--------\n"
- go test ./...
- env GOOS=${goos} GOARCH=${goarch} go build -v -ldflags "${ldflags}"
- file ${REPO_NAME}
- |-
  if [ -z "${TRAVIS_TAG}" ]; then
    TAG_SUFFIX=
  else
    echo "TRAVIS_TAG is ${TRAVIS_TAG}"
    TAG_SUFFIX=_${TRAVIS_TAG}
    mv ${REPO_NAME} ${REPO_NAME}${TAG_SUFFIX}
  fi
- zip -j ${REPO_NAME}_${goos}_${goarch}${TAG_SUFFIX}.zip ${REPO_NAME}${TAG_SUFFIX}

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "${REPO_NAME}_${goos}_${goarch}${TAG_SUFFIX}.zip"
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
  - master
  - /^release-v.+\..+\..+$/
  - /^v\d+\.\d+\.\d+(-\S*)?$/
