language: go

go:
- 1.11.x

env:
  global:
  - REPO_OWNER=guangie88
  - REPO_NAME=terraform-provider-smallutil

matrix:
  include:
    - env:
      - GOOS="linux"
      - GOARCH="386"
      - LDFLAGS="-linkmode external -extldflags -static -s -w"
    - env:
      - GOOS="linux"
      - GOARCH="amd64"
      - LDFLAGS="-linkmode external -extldflags -static -s -w"
    - env:
      - GOOS="linux"
      - GOARCH="arm"
      - LDFLAGS="-linkmode external -extldflags -static -s -w"
    - env:
      - GOOS="linux"
      - GOARCH="arm64"
      - LDFLAGS="-linkmode external -extldflags -static -s -w"
    - env:
      - GOOS="darwin"
      - GOARCH="386"
      - LDFLAGS="-linkmode external -extldflags -static -s -w"
    - env:
      - GOOS="darwin"
      - GOARCH="amd64"
      - LDFLAGS="-linkmode external -extldflags -static -s -w"
    - env:
      - GOOS="darwin"
      - GOARCH="arm"
      - LDFLAGS="-linkmode external -extldflags -static -s -w"
    - env:
      - GOOS="darwin"
      - GOARCH="arm64"
      - LDFLAGS="-linkmode external -extldflags -static -s -w"
    - env:
      - GOOS="windows"
      - GOARCH="386"
      - LDFLAGS="-linkmode external -extldflags -static -s -w"
    - env:
      - GOOS="windows"
      - GOARCH="amd64"
      - LDFLAGS="-linkmode external -extldflags -static -s -w"
  
script:
- env GOOS=${GOOS} GOARCH=${GOARCH} go build -v -ldflags "${LDFLAGS}"
- mv ${REPO_NAME} ${REPO_NAME}_${GOOS}_${GOARCH}
# - |-
#   ghr -t ${GITHUB_TOKEN} -u ${REPO_OWNER} -r ${REPO_NAME} \
#   -c ${CF_REVISION} -replace ${TAG_NAME} ltrigger.zip

branches:
  only:
  - master
